/*
 * generated by Xtext 2.31.0
 */
package qubo.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQUBOScopeProvider extends DelegatingScopeProvider {
}
